import { UseControllerProps } from 'react-hook-form';
import { IAllProps } from '@tinymce/tinymce-react';
import { Editor as EditorType } from 'tinymce';
import '../../vendors/tinymce/tinymce.min.js';
import '../../vendors/tinymce/models/dom/model.min.js';
import '../../vendors/tinymce/themes/silver/theme.min.js';
import '../../vendors/tinymce/icons/default/icons.min.js';
import '../../vendors/tinymce/skins/ui/oxide/skin.min.js';
import '../../vendors/tinymce/plugins/advlist/plugin.min.js';
import '../../vendors/tinymce/plugins/anchor/plugin.min.js';
import '../../vendors/tinymce/plugins/autolink/plugin.min.js';
import '../../vendors/tinymce/plugins/autoresize/plugin.min.js';
import '../../vendors/tinymce/plugins/autosave/plugin.min.js';
import '../../vendors/tinymce/plugins/charmap/plugin.min.js';
import '../../vendors/tinymce/plugins/code/plugin.min.js';
import '../../vendors/tinymce/plugins/codesample/plugin.min.js';
import '../../vendors/tinymce/plugins/directionality/plugin.min.js';
import '../../vendors/tinymce/plugins/emoticons/plugin.min.js';
import '../../vendors/tinymce/plugins/fullscreen/plugin.min.js';
import '../../vendors/tinymce/plugins/help/plugin.min.js';
import '../../vendors/tinymce/plugins/image/plugin.min.js';
import '../../vendors/tinymce/plugins/importcss/plugin.min.js';
import '../../vendors/tinymce/plugins/insertdatetime/plugin.min.js';
import '../../vendors/tinymce/plugins/link/plugin.min.js';
import '../../vendors/tinymce/plugins/lists/plugin.min.js';
import '../../vendors/tinymce/plugins/media/plugin.min.js';
import '../../vendors/tinymce/plugins/nonbreaking/plugin.min.js';
import '../../vendors/tinymce/plugins/pagebreak/plugin.min.js';
import '../../vendors/tinymce/plugins/preview/plugin.min.js';
import '../../vendors/tinymce/plugins/quickbars/plugin.min.js';
import '../../vendors/tinymce/plugins/save/plugin.min.js';
import '../../vendors/tinymce/plugins/searchreplace/plugin.min.js';
import '../../vendors/tinymce/plugins/table/plugin.min.js';
import '../../vendors/tinymce/plugins/visualblocks/plugin.min.js';
import '../../vendors/tinymce/plugins/visualchars/plugin.min.js';
import '../../vendors/tinymce/plugins/wordcount/plugin.min.js';
import '../../vendors/tinymce/plugins/emoticons/js/emojis.js';
import '../../vendors/tinymce/skins/content/default/content.js';
import '../../vendors/tinymce/skins/ui/oxide/content.js';
type Props = UseControllerProps & {
    editorProps?: IAllProps;
    onEditorChange?: (value: string, editor: EditorType) => string;
    onInit?: (event: any, editor: EditorType) => void;
    handleBlur?: Function;
    hideModalButtons?: boolean;
    simplifyEditor?: boolean;
    disabled?: boolean;
    placeholder?: string;
    imagesUploadHandler: any;
    addVideoEditorPlugin: Function;
    tinyKey: string;
    fontsURL: string;
};
declare function FormRichEditor({ editorProps, onEditorChange, onInit, handleBlur, hideModalButtons, simplifyEditor, placeholder, disabled, imagesUploadHandler, addVideoEditorPlugin, tinyKey, fontsURL, ...props }: Props): import("react/jsx-runtime").JSX.Element;
export default FormRichEditor;
