import { UseControllerProps } from 'react-hook-form';
import { IAllProps } from '@tinymce/tinymce-react';
import { Editor as EditorType } from 'tinymce';
import '../../vendors/tinymce/tinymce.min.js';
import '../../vendors/tinymce/models/dom/model.min.js';
import '../../vendors/tinymce/themes/silver/theme.min.js';
import '../../vendors/tinymce/icons/default/icons.min.js';
import '../../vendors/tinymce/skins/ui/oxide/skin.min.js';
import '../../vendors/tinymce/plugins/advlist';
import '../../vendors/tinymce/plugins/anchor';
import '../../vendors/tinymce/plugins/autolink';
import '../../vendors/tinymce/plugins/autoresize';
import '../../vendors/tinymce/plugins/autosave';
import '../../vendors/tinymce/plugins/charmap';
import '../../vendors/tinymce/plugins/code';
import '../../vendors/tinymce/plugins/codesample';
import '../../vendors/tinymce/plugins/directionality';
import '../../vendors/tinymce/plugins/emoticons';
import '../../vendors/tinymce/plugins/fullscreen';
import '../../vendors/tinymce/plugins/help';
import '../../vendors/tinymce/plugins/image';
import '../../vendors/tinymce/plugins/importcss';
import '../../vendors/tinymce/plugins/insertdatetime';
import '../../vendors/tinymce/plugins/link';
import '../../vendors/tinymce/plugins/lists';
import '../../vendors/tinymce/plugins/media';
import '../../vendors/tinymce/plugins/nonbreaking';
import '../../vendors/tinymce/plugins/pagebreak';
import '../../vendors/tinymce/plugins/preview';
import '../../vendors/tinymce/plugins/quickbars';
import '../../vendors/tinymce/plugins/save';
import '../../vendors/tinymce/plugins/searchreplace';
import '../../vendors/tinymce/plugins/table';
import '../../vendors/tinymce/plugins/visualblocks';
import '../../vendors/tinymce/plugins/visualchars';
import '../../vendors/tinymce/plugins/wordcount';
import '../../vendors/tinymce/plugins/emoticons/js/emojis.js';
import '../../vendors/tinymce/skins/content/default/content.js';
import '../../vendors/tinymce/skins/ui/oxide/content.js';
type Props = UseControllerProps & {
    editorProps?: IAllProps;
    onEditorChange?: (value: string, editor: EditorType) => string;
    onInit?: (event: any, editor: EditorType) => void;
    handleBlur?: Function;
    hideModalButtons?: boolean;
    simplifyEditor?: boolean;
    disabled?: boolean;
    placeholder?: string;
    imagesUploadHandler: any;
    addVideoEditorPlugin: Function;
    tinyKey: string;
    fontsURL: string;
};
declare function FormRichEditor({ editorProps, onEditorChange, onInit, handleBlur, hideModalButtons, simplifyEditor, placeholder, disabled, imagesUploadHandler, addVideoEditorPlugin, tinyKey, fontsURL, ...props }: Props): import("react/jsx-runtime").JSX.Element;
export default FormRichEditor;
